# Generated by Django 6.0.4 on 2026-04-09 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planned_meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('cooked', 'Cooked'), ('skipped', 'Skipped')], max_length=20)),
                ('liked', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planned_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='planned_meal.plannedmeal')),
            ],
        ),
    ]
