# Generated by Django 6.0.4 on 2026-04-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealfeedback',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mealfeedback',
            name='status',
            field=models.CharField(choices=[('cooked', 'Cooked'), ('skipped', 'Skipped')], max_length=20),
        ),
    ]
