# Generated by Django 6.0.4 on 2026-04-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekly_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_list', to='weekly_plan.weeklyplan')),
            ],
        ),
    ]
