# Generated by Django 6.0.4 on 2026-04-09 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weekly_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('estimated_time', models.IntegerField(blank=True, null=True)),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='weekly_plan.weeklyplan')),
            ],
        ),
    ]
