# Generated by Django 6.0.4 on 2026-04-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planned_meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plannedmeal',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='plannedmeal',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='plannedmeal',
            name='name',
        ),
        migrations.AddField(
            model_name='plannedmeal',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plannedmeal',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_instances', to='planned_meal.meal'),
        ),
    ]
